prom3theu5/aspirational-manifests

Directory.Packages.props, src/Aspirate.Cli/Aspirate.Cli.csproj, src/Aspirate.Cli/Commands/EndToEnd/EndToEndCommand.cs, src/Aspirate.Cli/Extensions/ServiceCollectionExtensions.cs, src/Aspirate.Cli/GlobalUsings.cs, src/Aspirate.Cli/Logging/LoggerMessages.cs, src/Aspirate.Cli/Processors/Components/Final/FinalProcessor.cs, src/Aspirate.Cli/Processors/Components/Postgresql/PostgresDatabaseProcessor.cs, src/Aspirate.Cli/Processors/Components/Postgresql/PostgresServerProcessor.cs, src/Aspirate.Cli/Processors/Components/Project/ProjectProcessor.cs, src/Aspirate.Cli/Program.cs, src/Aspirate.Cli/Services/ManifestFileParserService.cs, src/Aspirate.Cli/Services/ProjectPropertyService.cs, src/Aspirate.Contracts/Aspirate.Contracts.csproj, src/Aspirate.Contracts/GlobalUsings.cs, src/Aspirate.Contracts/Processors/BaseProcessor.cs
=> Add logging support (serilog)

src/Aspirate.Cli/Extensions/ServiceCollectionExtensions.cs, src/Aspirate.Cli/GlobalUsings.cs, src/Aspirate.Cli/Processors/Components/Final/FinalTemplateData.cs, src/Aspirate.Cli/Processors/Components/Postgresql/PostgresDatabaseTemplateData.cs, src/Aspirate.Cli/Processors/Components/Postgresql/PostgresServerTemplateData.cs, src/Aspirate.Cli/Processors/Components/Project/ProjectProcessor.cs, src/Aspirate.Cli/Processors/Components/Project/ProjectTemplateData.cs, src/Aspirate.Cli/Processors/Components/Redis/RedisProcessor.cs, src/Aspirate.Cli/Processors/Components/Redis/RedisTemplateData.cs, src/Aspirate.Cli/Templates/deployment.hbs, src/Aspirate.Cli/Templates/kustomization.hbs, src/Aspirate.Cli/Templates/postgres-server.hbs, src/Aspirate.Cli/Templates/redis.hbs, src/Aspirate.Cli/Templates/service.hbs, src/Aspirate.Contracts/Interfaces/IProcessor.cs, src/Aspirate.Contracts/Literals/AspireResourceLiterals.cs, src/Aspirate.Contracts/Literals/TemplateLiterals.cs, src/Aspirate.Contracts/Models/AspireManifests/Components/V0/Redis.cs, src/Aspirate.Contracts/Processors/BaseProcessor.cs, src/Aspirate.Contracts/Processors/BaseTemplateData.cs
includes Redis and Postgres deployments now - handles #2
=> Add templates based on eShopLite

src/Aspirate.Cli/Commands/EndToEnd/EndToEndCommand.cs, src/Aspirate.Cli/Commands/Init/InitCommand.cs, src/Aspirate.Cli/Extensions/PathExtensions.cs, src/Aspirate.Contracts/Processors/BaseProcessor.cs
when running the init command, you have the ability to select a custom template directory.
These changes, check if the directory exists, and contains files
If it doesn't exist it will ask if it should be created, then it will ask if you want to populate files
If you say yes, the default templates packed with the tool, will be populated into your custom template directory so you can get straight to editing them. have fun!
=> Bootstrap the template folder

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/user-story.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .github/workflows/main.yml, .github/workflows/pull-requests.yml, Aspirate.sln, Directory.Packages.props, build.cake, dotnet-tools.json, src/Aspirate.Cli/Aspirate.Cli.csproj
Adds the github actions for PR, and Release to GitHub on new tag pushes.
Also adds some templates
=> Nuget release actions

src/Aspirate.Cli/Actions/Containers/BuildAndPushContainersAction.cs, src/Aspirate.Cli/Actions/Containers/PopulateContainerDetailsAction.cs, src/Aspirate.Cli/Actions/Manifests/GenerateKustomizeManifestAction.cs
This PR skips execution of project processing if no project resources have been selected.
=> Dont execute these actions if no items to process.

src/Aspirate.Cli/Actions/Containers/BuildAndPushContainersAction.cs, src/Aspirate.Cli/Actions/Manifests/LoadAspireManifestAction.cs, src/Aspirate.Cli/Commands/Generate/GenerateCommand.cs, src/Aspirate.Cli/Commands/Generate/GenerateOptions.cs, src/Aspirate.Cli/Commands/SharedOptions.cs, src/Aspirate.Cli/Processors/Components/Project/ProjectProcessor.cs, src/Aspirate.Cli/Services/ContainerCompositionService.cs, src/Aspirate.Shared/Models/State/AspirateState.cs, src/Aspirate.Shared/Services/IContainerCompositionService.cs
=> 37 Any prompt input should be allowable args in the CLI

src/Aspirate.Cli/AspirateCli.cs, src/Aspirate.Cli/Commands/Build/BuildCommand.cs, src/Aspirate.Cli/Commands/Build/BuildCommandHandler.cs, src/Aspirate.Cli/Commands/Build/BuildOptions.cs, src/Aspirate.Cli/GlobalUsings.cs, src/Aspirate.Cli/Properties/launchSettings.json
useful if you need to make edits to containers, and dont want to lose your custom edits to manifest files
=> Add build command

README.md
The README file was updated to include a comprehensive section on Secrets Management. These changes improve the documentation for managing secure, encrypted data such as connection strings. New instructions have been added for generating, applying, and disabling secrets, enhancing the tool's use experience and security. The Table of Contents was also updated accordingly.
=> Update README with Secrets Management section

docs/Writerside/c.list, docs/Writerside/hi.tree, docs/Writerside/topics/Apply-Manifests.md, docs/Writerside/topics/Applying-Secrets.md, docs/Writerside/topics/Build-Command.md, docs/Writerside/topics/Commands.md, docs/Writerside/topics/Disable-Secret-Management.md, docs/Writerside/topics/General-FAQ.md, docs/Writerside/topics/Generate-Command.md, docs/Writerside/topics/Generating-Secrets.md, docs/Writerside/topics/Getting-Started.md, docs/Writerside/topics/Init-Command.md, docs/Writerside/topics/Installing-as-a-Global-Tool.md, docs/Writerside/topics/Managing-Secrets.md, docs/Writerside/topics/Non-Interactive-Invocation.md, docs/Writerside/topics/Removing-Aspirate.md, docs/Writerside/topics/Removing-Manifests-from-a-Cluster.md, docs/Writerside/topics/Secret-Management.md, docs/Writerside/topics/Secrets-File-Contents.md, docs/Writerside/v.list, docs/Writerside/writerside.cfg
This update includes the addition of several documents under the Writerside folder, providing extensive instructions and guides for the 'aspirate' product. Also added are XML configuration files for defining categories, variables, instances, and document structure. These additions enhance the documentation, simplifying feature usage for users.
#9
=> Add Writerside documentation and XML configuration files

src/Aspirate.Cli/Templates/service.hbs, src/Aspirate.Processors/KubernetesDeploymentTemplateData.cs, src/Aspirate.Processors/PlaceholderSubstitutionStrategies/ResourceContainerConnectionStringSubstitutionStrategy.cs, src/Aspirate.Processors/PlaceholderSubstitutionStrategies/ResourceGenericConnectionStringSubstitutionStrategy.cs, src/Aspirate.Processors/Resources/Container/ContainerProcessor.cs, tests/Aspirate.Tests/ServiceTests/ManifestFileParserServiceTests.cs, tests/Aspirate.Tests/TestData/preview-2-manifest.json
=> 90 Difference in PSQL containers between new project & eShopLite when deployed

src/Aspirate.Services/Implementations/ContainerCompositionService.cs, src/Aspirate.Services/Implementations/DaprCliService.cs, src/Aspirate.Services/Implementations/ShellExecutionService.cs, src/Aspirate.Services/Interfaces/IShellExecutionService.cs, src/Aspirate.Shared/Models/Aspirate/CommandAvailableResult.cs, tests/Aspirate.Tests/ServiceTests/ContainerCompositionServiceTest.cs
The new class, CommandAvailableResult, has been added for returning availability and path of commands, rather than just a bool. This class is utilized within the IShellExecutionService interface and its implementations, specifically affecting the IsCommandAvailable method. Tests are updated to incorporate this change.
This will give more information now when executing the check for the builder running as raised in issue #94
=> Add CommandAvailableResult class and update IShellExecutionService

src/Aspirate.Cli/Templates/deployment.hbs, src/Aspirate.Cli/Templates/kustomization.hbs, src/Aspirate.Cli/Templates/service.hbs, src/Aspirate.Processors/FinalProcessor.cs, src/Aspirate.Processors/KubernetesDeploymentTemplateData.cs, src/Aspirate.Processors/PlaceholderSubstitutionStrategies/ResourceContainerConnectionStringSubstitutionStrategy.cs, src/Aspirate.Processors/Resources/Container/ContainerProcessor.cs, src/Aspirate.Processors/Resources/Project/ProjectProcessor.cs, src/Aspirate.Shared/Models/AspireManifests/Components/V0/Container/ContainerResource.cs, src/Aspirate.Shared/Models/AspireManifests/Interfaces/IResourceWithArgs.cs
The code now supports arguments for containers, enhancing its flexibility. Additional null checks have been added wherever necessary within the manifest validation process. Some unnecessary parameters have been removed to streamline processing and enhance efficiency. The ASPNETCORE_URLS environment variable was adjusted for more SSL validation.
=> Add support for container arguments and enhance null checks

src/Aspirate.Processors/GlobalUsings.cs, src/Aspirate.Processors/Transformation/ResourceExpressionProcessor.cs, tests/Aspirate.Tests/Aspirate.Tests.csproj, tests/Aspirate.Tests/ServiceTests/ManifestFileParserServiceTests.cs, tests/Aspirate.Tests/TestData/with-unsupported-resource.json
=> 159 UnsupportedResource Exception when running 'generate'

src/Aspirate.Shared/Models/AspireManifests/Resource.cs
=> 161 Dapr Components are currently breaking the build / generate process

src/Aspirate.Cli/Templates/dapr-component.hbs, src/Aspirate.Cli/Templates/deployment.hbs, src/Aspirate.Cli/Templates/statefulset.hbs, src/Aspirate.Commands/Actions/Manifests/ApplyDaprAnnotationsAction.cs, src/Aspirate.Commands/Actions/Manifests/GenerateHelmChartAction.cs
=> Ensure annotations are applied correctly for dapr components

Directory.Packages.props, src/Aspirate.Cli/AspirateCli.cs, src/Aspirate.Cli/GlobalUsings.cs, src/Aspirate.Commands/Commands/BaseCommand.cs, src/Aspirate.Commands/Commands/BaseCommandOptionsHandler.cs, src/Aspirate.Commands/Commands/GenericCommand.cs, src/Aspirate.Commands/Commands/Settings/SettingsCommand.cs, src/Aspirate.Commands/GlobalUsings.cs, src/Aspirate.Services/Aspirate.Services.csproj, src/Aspirate.Services/GlobalUsings.cs, src/Aspirate.Services/Implementations/VersionCheckService.cs, src/Aspirate.Services/ServiceCollectionExtensions.cs, src/Aspirate.Shared/Extensions/PathExtensions.cs, src/Aspirate.Shared/Interfaces/Services/IVersionCheckService.cs, src/Aspirate.Shared/Literals/AspirateLiterals.cs, src/Aspirate.Shared/Literals/AspireLiterals.cs, src/Aspirate.Shared/Models/Aspirate/LastVersionChecked.cs
Also adds settings commands and sub commands, with option to show / hide the local, and option to disable / enable the newly added version check which will check nuget for latest package version between command runs every run and notify you of an update.
=> Update to preview 7

src/Aspirate.Shared/Models/Aspirate/KubernetesDeploymentData.cs
=> 194 Generate kustomize manifest for angular (AddNpmApp) fails

src/Aspirate.Commands/Actions/Manifests/GenerateDockerComposeManifestAction.cs, src/Aspirate.Commands/Actions/Manifests/GenerateKustomizeManifestsAction.cs, src/Aspirate.Processors/Resources/Dapr/DaprProcessor.cs, src/Aspirate.Shared/Inputs/BaseCreateOptions.cs, src/Aspirate.Shared/Models/Aspirate/AspirateState.cs, src/Aspirate.Shared/Models/Compose/ComposeService.cs, src/Aspirate.Shared/Models/Compose/ComposeServiceBuilder.cs
Dapr sidecar containers weren't created for compose output format - this fixes that #166
=> 166 Dapr sidecars not being added to docker compose

README.md
Remove default prerelease option for installation command
=> Update readme after GA release

src/Aspirate.Services/Implementations/KubeCtlService.cs, src/Aspirate.Services/Implementations/KubernetesService.cs, src/Aspirate.Shared/Literals/KubeCtlLiterals.cs
Adds `fieldManager`, `pretty`, and `fieldValidation` options to the resource
creation methods in KubernetesService and KubeCtlService for better
management and validation.
=> feat: Add fieldManager, pretty, and fieldValidation options to resource creation
