prom3theu5/aspirational-manifests

src/Aspirate.Cli/Aspirate.Cli.csproj

Fix #20 
This pull request adds the PackAsTool property to the csproj file, allowing the project to be packed as a tool.
This was preventing me from using dotnet tool install on Windows as the package type was missing.

Add PackAsTool property to csproj file

---

README.md
src/Aspirate.Cli/Commands/EndToEnd/EndToEndCommand.cs
src/Aspirate.Cli/Processors/Components/Project/ProjectProcessor.cs
src/Aspirate.Contracts/Literals/EmojiLiterals.cs
src/Aspirate.Contracts/Processors/BaseProcessor.cs

Also add sttement to README about powershell and cmd, we don't want to really override the encoding of the users console from our application.

Remove copypastas, use known emoji from spectre

---

src/Aspirate.Cli/Actions/ActionExecutor.cs
src/Aspirate.Cli/Actions/Manifests/ApplyManifestsToClusterAction.cs
src/Aspirate.Cli/Actions/Manifests/RemoveManifestsFromClusterAction.cs
src/Aspirate.Cli/Services/ContainerCompositionService.cs
src/Aspirate.Cli/Services/KubeCtlService.cs
src/Aspirate.Contracts/Interfaces/IKubeCtlService.cs
src/Aspirate.Contracts/Models/State/ComputedParametersState.cs

Includes propagation of the correct exit code based on the failure action exception raised.
Also unpicks current selected active context from services, and moves it into state.
Fixed #41

41 If publish fails, aspirate still gives success status

---

README.md
src/Aspirate.Cli/Actions/Manifests/GenerateAspireManifestAction.cs
src/Aspirate.Cli/Actions/Manifests/LoadAspireManifestAction.cs
src/Aspirate.Cli/AspirateCli.cs
src/Aspirate.Cli/Commands/Build/BuildCommand.cs
src/Aspirate.Cli/Commands/Build/BuildOptions.cs
src/Aspirate.Cli/Commands/Generate/GenerateCommand.cs
src/Aspirate.Cli/Commands/Generate/GenerateOptions.cs
src/Aspirate.Cli/Commands/SharedOptions.cs
src/Aspirate.Shared/Models/State/AspirateState.cs

Very useful if you just want to rebuild and push containers as it immediately shows the menu of items within the manifest, for you to select items from

Allows skipping the aspire manifest rebuild by passing in -m ./manifest.json

---

src/Aspirate.Cli/Properties/launchSettings.json
src/Aspirate.Cli/Templates/redis.hbs
src/Aspirate.Commands/Actions/Manifests/ApplyManifestsToClusterAction.cs
src/Aspirate.Commands/Actions/Manifests/GenerateKustomizeManifestsAction.cs
src/Aspirate.Commands/Actions/Manifests/RemoveManifestsFromClusterAction.cs
src/Aspirate.Commands/Actions/Secrets/LoadSecretsAction.cs
src/Aspirate.Commands/Actions/Secrets/PopulateInputsAction.cs
src/Aspirate.Commands/Actions/Secrets/SaveSecretsAction.cs
src/Aspirate.Commands/AspirateState.cs
src/Aspirate.Commands/Commands/BaseCommand.cs
src/Aspirate.Commands/Commands/BaseCommandOptions.cs
src/Aspirate.Processors/BaseProcessor.cs
src/Aspirate.Processors/Container/ContainerProcessor.cs
src/Aspirate.Processors/Dockerfile/DockerfileProcessor.cs
src/Aspirate.Processors/Postgresql/PostgresDatabaseProcessor.cs
src/Aspirate.Processors/Postgresql/PostgresServerProcessor.cs
src/Aspirate.Processors/Project/ProjectProcessor.cs
src/Aspirate.Processors/RabbitMQ/RabbitMQProcessor.cs
src/Aspirate.Processors/Redis/RedisProcessor.cs
src/Aspirate.Shared/Processors/IProcessor.cs

This update introduces the ability to disable secret generation across the Aspirate Project. A "DisableSecrets" option is added, which when set to true, turns off all secret generations. This is particularly useful when secret generation is unnecessary or poses unnecessary overhead. The update also changes the Docker image for Redis to use the latest version, instead of a specific version.

Add option to disable secret generation

---

src/Aspirate.Secrets/BaseSecretProvider.cs

This update makes sure a directory is created in the file system if it does not exist. This change was made in the BaseSecretProvider class and ensures that the file system path is ready to write, preventing failures due to a non-existing directory.

Create directory if not existing in BaseSecretProvider

---

src/Aspirate.Cli/Aspirate.Cli.csproj
src/Aspirate.Cli/Templates/sqlserver.hbs
src/Aspirate.Commands/AspirateState.cs
src/Aspirate.Processors/BaseProcessor.cs
src/Aspirate.Processors/Extensions/ServiceCollectionExtensions.cs
src/Aspirate.Processors/GlobalUsings.cs
src/Aspirate.Processors/SqlServer/SqlServerDatabaseProcessor.cs
src/Aspirate.Processors/SqlServer/SqlServerDatabaseTemplateData.cs
src/Aspirate.Processors/SqlServer/SqlServerProcessor.cs
src/Aspirate.Processors/SqlServer/SqlServerTemplateData.cs
src/Aspirate.Shared/Extensions/StringExtensions.cs
src/Aspirate.Shared/GlobalUsings.cs
src/Aspirate.Shared/Literals/AspireLiterals.cs
src/Aspirate.Shared/Literals/TemplateLiterals.cs
src/Aspirate.Shared/Models/AspireManifests/Components/V1/SqlServer.cs
src/Aspirate.Shared/Models/AspireManifests/Components/V1/SqlServerDatabase.cs
tests/Aspirate.Tests/ActionsTests/Manifests/LoadAspireManifestActionTests.cs
tests/Aspirate.Tests/GlobalUsings.cs
tests/Aspirate.Tests/ServiceTests/ManifestFileParserServiceTests.cs
tests/Aspirate.Tests/TestData/manifest.json

This update includes the support for SQL Server related versions, including the addition of new classes and updating existing classes to accommodate SQL Server related operations. Additionally, new tests were updated to include SQL Server cases.

Add support for SQL Server manifests and templates

---

src/Aspirate.Commands/Actions/Manifests/ApplyManifestsToClusterAction.cs
src/Aspirate.Commands/Actions/Manifests/RemoveManifestsFromClusterAction.cs
src/Aspirate.Processors/Dockerfile/DockerfileProcessor.cs
src/Aspirate.Processors/Dockerfile/DockerfileTemplateData.cs
src/Aspirate.Processors/GlobalUsings.cs
src/Aspirate.Services/Implementations/ContainerCompositionService.cs
src/Aspirate.Services/Interfaces/IContainerCompositionService.cs

The commit adds a check for secret state before processing secretProvider in the RemoveManifestsFromClusterAction and ApplyManifestsToClusterAction classes. Also, it makes the Docker container registry optional across different classes, appending the registry to the image tag only when provided. Finally, an imagePullPolicy was included in Dockerfile processors to manage Docker image pulling more effectively.
This fixes #70

70 'Object reference not set to an instance of an object' while deploying

---

src/Aspirate.Services/Implementations/ContainerCompositionService.cs
tests/Aspirate.Tests/ServiceTests/ContainerCompositionServiceTest.cs

Container Composition Service has been updated to ensure that dockerfile environmental variables pass through the variables as --build-args when building containers.
Unit tests have been updated to ensure the results of the argument builder are the expected values.
Workaround for #75

75 QA: ENV variables while deploying Node apps with Dockerfile

---

src/Aspirate.Commands/Actions/Containers/BuildAndPushContainersFromProjectsAction.cs
src/Aspirate.Processors/Resources/Project/ProjectProcessor.cs

The --runtime-identifier parameter is being ignored when building containers from project. It always defaults to "linux-x64"

Fix runtime identifier being ignored

---

src/Aspirate.Commands/Actions/Configuration/InitializeConfigurationAction.cs
src/Aspirate.Commands/Options/ContainerRepositoryPrefixOption.cs

Also adds -crp as shorthand version

117 `--container-repository-prefix` doesn't respect `--non-interactive`

---

src/Aspirate.Shared/Models/AspireManifests/Components/UnsupportedResource.cs

The previous implementation hide a value for type which lead to a null reference exception
Closes #138

set constant value for type on UnsupportedResource.cs

---

src/Aspirate.Services/Extensions/JsonExtensions.cs
src/Aspirate.Services/Implementations/ContainerCompositionService.cs
tests/Aspirate.Tests/ServiceTests/ContainerCompositionServiceTest.cs

This implementation fixes exceptions that occurs in ValidateBuilderOutput when we don't have valid json in builderCheckResult.Output.
Fixes (#148)

fix json parse error in ValidateBuilderOutput (#148)

---

src/Aspirate.Cli/Templates/dashboard.hbs
src/Aspirate.Cli/Templates/kustomization.hbs
src/Aspirate.Commands/Actions/Manifests/GenerateDockerComposeManifestAction.cs
src/Aspirate.Shared/Extensions/ResourceExtensions.cs

Also - no need to expose port 18889 on the host, as comms will work internally on the docker network compose creates.

172 Dashboard does not work with docker compose

---

src/Aspirate.Commands/Commands/BaseCommand.cs
src/Aspirate.Services/Implementations/StateService.cs

Ensures that state management works in none interactive mode, and also add the disable state option to the BaseCommand options (doh! - missed that one). Fixes #183

183 StateManagement breaks existing non-interactive build with disabled secrets

---

src/Aspirate.Cli/Templates/dashboard.hbs
src/Aspirate.Services/Implementations/KubernetesService.cs
src/Aspirate.Shared/Literals/AspireLiterals.cs
src/Aspirate.Shared/Models/AspireManifests/AspireDashboard.cs

- New image `mcr.microsoft.com/dotnet/aspire-dashboard:8.0`
- Remove readiness probe from aspire dashboard so it starts instantly under k8s (including `aspirate run`, no more 30 second delay
- Ensure http named ports get exposed as nodeport in `aspirate run` (such as the AspireJavascript example project)

Update aspire dasjhboard image to ga image

---

src/Aspirate.Services/Implementations/ContainerCompositionService.cs
src/Aspirate.Shared/Literals/DotNetSdkLiterals.cs

This commit introduces changes to the ContainerCompositionService and DotNetSdkLiterals source files. Specifically in the ContainerCompositionService file, it modifies the PublishProfileArgument to ContainerTargetArgument, with an empty string value. A few additions were also made to the DotNetSdkLiterals file, including the addition of the ContainerTargetArgument and the removal of the ContainerPublishProfile constant.

219 Will not publish containers for non-web projects

---

src/Aspirate.Commands/Commands/BaseCommand.cs
src/Aspirate.Services/Implementations/ContainerDetailsService.cs
src/Aspirate.Shared/Extensions/DockerfileParametersExtensions.cs
tests/Aspirate.Tests/ServiceTests/VerifyResults/ContainerOptionsTests.ContainerParametersFullyPopulated_ShouldPopulateImageCorrectly_testOptions=FullParameters.verified.txt
tests/Aspirate.Tests/ServiceTests/VerifyResults/ContainerOptionsTests.ContainerParametersFullyPopulated_ShouldPopulateImageCorrectly_testOptions=ImageAndTag.verified.txt
tests/Aspirate.Tests/ServiceTests/VerifyResults/ContainerOptionsTests.ContainerParametersFullyPopulated_ShouldPopulateImageCorrectly_testOptions=RegistryAndPrefixAndImage.verified.txt

To include multiple tags, specify -ct multiple times with a tag for each

Ensure that the latest tag isn't applied to all container builds when specifying -ct

---

src/Aspirate.Processors/Transformation/Bindings/BindingProcessor.cs
src/Aspirate.Processors/Transformation/Literals.cs

Bug fix
___
- Added support for the `scheme` property in endpoint bindings (#275)
- Extended the binding processor to handle scheme property replacement
- Added new constant definition for `scheme` in Literals class
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>BindingProcessor.cs</strong><dd><code>Add scheme property support in binding processor</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/Aspirate.Processors/Transformation/Bindings/BindingProcessor.cs
<li>Added support for <code>scheme</code> property in binding replacement logic<br> <li> Extended switch statement to handle the new <code>Scheme</code> property …

fix(#275): add support for the scheme property in endpoint bindings

---

src/Aspirate.Commands/Actions/Secrets/PopulateInputsAction.cs
src/Aspirate.Commands/Commands/Generate/GenerateCommand.cs
src/Aspirate.Commands/Commands/Generate/GenerateOptions.cs
src/Aspirate.Commands/Options/ParameterResourceValueOption.cs
src/Aspirate.Shared/Interfaces/Commands/Contracts/IGenerateOptions.cs
src/Aspirate.Shared/Models/Aspirate/AspirateState.cs

resolves https://github.com/prom3theu5/aspirational-manifests/issues/274
Allows to set parameters to `generate` command from command line: `generate --parameter Key1=Value1 --parameter Key2=Value2`.
Useful when used in non-interactive mode.
___
Enhancement
___
- Added support for specifying manifest parameters in non-interactive mode.
- Introduced new option `--parameter` for `generate` command.
- Implemented logic to override parameter values programmatically.
- Updated state and interfaces to handle parameter overrides.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>PopulateInputsAction.cs</strong><dd><code>Implement parameter override handling in …

Possibility to specify manifest parameter values for generate command in non interactive mode (#274)

---

src/Aspirate.Commands/Actions/Manifests/GenerateDockerComposeManifestAction.cs
tests/Aspirate.Tests/DockerComposeTests/DockerComposeBuilderTests.cs
tests/Aspirate.Tests/DockerComposeTests/VerifyResults/DockerComposeBuilderTests.SerializeComposeFile_WithExposedPort_ShouldBeValid.verified.txt
tests/Aspirate.Tests/DockerComposeTests/VerifyResults/DockerComposeBuilderTests.SerializeComposeFile_WithExposedPorts_ShouldBeValid.verified.txt

fix: docker compose port serialization. ComposeBuilder library doesn't automatically register the port type converter.

---

src/Aspirate.Commands/Actions/Containers/BuildAndPushContainersFromProjectsAction.cs
src/Aspirate.Commands/Actions/Containers/PopulateContainerDetailsForProjectsAction.cs
src/Aspirate.Processors/Resources/AbstractProcessors/BaseContainerProcessor.cs
src/Aspirate.Processors/Resources/AbstractProcessors/ContainerProcessor.cs
src/Aspirate.Processors/Resources/AbstractProcessors/ContainerV1Processor.cs
src/Aspirate.Processors/Resources/Project/BaseProjectProcessor.cs
src/Aspirate.Processors/Resources/Project/ProjectV1Processor.cs
src/Aspirate.Processors/ServiceCollectionExtensions.cs
src/Aspirate.Services/GlobalUsings.cs
src/Aspirate.Services/Implementations/ContainerDetailsService.cs
src/Aspirate.Shared/Literals/AspireComponentLiterals.cs
src/Aspirate.Shared/Models/AspireManifests/Components/Common/ProjectResource.cs

This PR adds support for the `project.v1` resource type. As described in #312, the use of methods such as `AddAzureContainerAppsInfrastructure` and `PublishAsAzureContainerApp` results in project resources appearing in the manifest as `project.v1` rather than `project.v0`. As per the manifest schema, the only current difference between the two is the presence of an Azure Bicep `deployment` property in v1. While this functionality cannot be supported, there may be scenarios where users still want to deploy to other targets despite the presence of Azure-specific configurations (also #312).
In alignment with the versioning strategy used to share functionality between `container.v0` and `container.v1`, core project processing functionality was moved to `BaseProjectProcessor`, from which …

project.v1 support
